FROM nginx:latest

ARG UID=1000
ARG GID=1000

ENV UID=${UID}
ENV GID=${GID}

RUN addgroup --gid ${GID} --system laravel \
    && adduser --ingroup laravel --system --disabled-password --shell /bin/sh --uid ${UID} laravel \
    && sed -i "s/user  nginx/user laravel/g" /etc/nginx/nginx.conf

COPY nginx-site.conf /etc/nginx/conf.d/default.conf

WORKDIR /var/www/html

# COPY . .